#!/bin/zsh
# Builds a signed, notarized and stapled Waypoint DMG for GitHub Releases.
#
#   scripts/release.sh 0.1.0             # → dist/Waypoint-0.1.0.dmg (+ .sha256)
#   scripts/release.sh 0.1.0 --publish   # …and publish it as GitHub release v0.1.0
#
#   SIGN_IDENTITY   Developer ID Application identity (default: first one in the keychain)
#   NOTARY_PROFILE  notarytool keychain profile (default: NotaryProfile). Create it once:
#                     xcrun notarytool store-credentials NotaryProfile --apple-id <apple id> --team-id <team id>
#   NOTARY_KEY, NOTARY_KEY_ID, NOTARY_ISSUER
#                   or notarize with an App Store Connect API key (.p8 path, key ID, issuer ID)
#   NOTES_FILE      release notes for --publish (default: generated by GitHub)
#   ALLOW_DIRTY=1   build from a working tree with uncommitted changes
set -euo pipefail
cd "${0:A:h}/.."

step() { print -P "%F{cyan}==>%f $*" }
fail() { print -P "%F{red}error:%f $*" >&2; exit 1 }

version="${1:-}"
publish=0
[[ "${2:-}" == "--publish" ]] && publish=1
[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "usage: scripts/release.sh <x.y.z> [--publish]"

tag="v$version"
profile="${NOTARY_PROFILE:-NotaryProfile}"
# Separate from build/Waypoint.app, which may be running.
app="build/release/Waypoint.app"
dist="dist"
dmg="$dist/Waypoint-$version.dmg"

# Preconditions first, so a missing credential doesn't cost a full build.
[[ -z "$(git status --porcelain)" || -n "${ALLOW_DIRTY:-}" ]] \
    || fail "working tree has uncommitted changes (ALLOW_DIRTY=1 to build anyway)"
identity="${SIGN_IDENTITY:-$(security find-identity -v -p codesigning | sed -n 's/.*"\(Developer ID Application:.*\)"/\1/p' | head -1)}"
[[ -n "$identity" ]] || fail "no Developer ID Application identity in the keychain"
if [[ -n "${NOTARY_KEY:-}" ]]; then
    [[ -n "${NOTARY_KEY_ID:-}" && -n "${NOTARY_ISSUER:-}" ]] || fail "NOTARY_KEY also needs NOTARY_KEY_ID and NOTARY_ISSUER"
    notary_auth=(--key "$NOTARY_KEY" --key-id "$NOTARY_KEY_ID" --issuer "$NOTARY_ISSUER")
    xcrun notarytool history "${notary_auth[@]}" >/dev/null 2>&1 || fail "Apple rejected the App Store Connect API key"
else
    notary_auth=(-p "$profile")
    xcrun notarytool history "${notary_auth[@]}" >/dev/null 2>&1 || fail "notarytool profile \"$profile\" is missing. Create it once with:
    xcrun notarytool store-credentials $profile --apple-id <apple id> --team-id <team id>
or set NOTARY_KEY, NOTARY_KEY_ID and NOTARY_ISSUER to use an App Store Connect API key"
fi
if (( publish )); then
    ! git rev-parse -q --verify "refs/tags/$tag" >/dev/null || fail "tag $tag already exists"
    git fetch -q origin
    git merge-base --is-ancestor HEAD origin/main || fail "HEAD is not on origin/main; push it first"
    gh auth status >/dev/null 2>&1 || fail "gh is not logged in"
fi

step "Testing"
xcrun swift test

step "Building Waypoint $version"
APP_PATH="$app" VERSION="$version" SIGN_IDENTITY="$identity" scripts/bundle.sh
codesign --verify --deep --strict "$app"
codesign -dvv "$app" 2>&1 | grep -q 'flags=.*runtime' || fail "hardened runtime is not enabled"

# notarize <file>: submit, wait, and on rejection print Apple's log.
notarize() {
    local file="$1" result
    result="$(mktemp)"
    step "Notarizing ${file:t} (usually a few minutes)"
    xcrun notarytool submit "$file" "${notary_auth[@]}" --wait --timeout 1h --output-format json >"$result" || true
    local notary_status id
    notary_status="$(plutil -extract status raw -o - "$result" 2>/dev/null || echo unknown)"
    if [[ "$notary_status" != "Accepted" ]]; then
        cat "$result" >&2
        id="$(plutil -extract id raw -o - "$result" 2>/dev/null || true)"
        [[ -n "$id" ]] && xcrun notarytool log "$id" "${notary_auth[@]}" >&2
        fail "notarization of ${file:t}: $notary_status"
    fi
    rm -f "$result"
}

rm -rf "$dist"
mkdir -p "$dist"

# The app first, so it carries its own ticket even outside the DMG.
zip="$dist/Waypoint-$version-app.zip"
ditto -c -k --keepParent "$app" "$zip"
notarize "$zip"
rm -f "$zip"
xcrun stapler staple "$app"

step "Packaging $dmg"
staging="$(mktemp -d)"
mount="$(mktemp -d)"
trap 'rm -rf "$staging"; hdiutil detach -quiet "$mount" 2>/dev/null || true; rmdir "$mount" 2>/dev/null || true' EXIT
ditto "$app" "$staging/Waypoint.app"
ln -s /Applications "$staging/Applications"
hdiutil create -quiet -volname "Waypoint $version" -srcfolder "$staging" -fs HFS+ -format UDZO -ov "$dmg"
codesign --force --sign "$identity" --timestamp "$dmg"
notarize "$dmg"
xcrun stapler staple "$dmg"

step "Verifying"
xcrun stapler validate "$dmg"
spctl --assess --type open --context context:primary-signature --verbose "$dmg"
hdiutil attach -quiet -nobrowse -readonly -mountpoint "$mount" "$dmg"
spctl --assess --type execute --verbose "$mount/Waypoint.app"
xcrun stapler validate "$mount/Waypoint.app"
hdiutil detach -quiet "$mount"
(cd "$dist" && shasum -a 256 "${dmg:t}" >"${dmg:t}.sha256")
print -P "%F{green}Ready:%f $dmg"

if (( publish )); then
    step "Publishing $tag"
    git tag -a "$tag" -m "Waypoint $version"
    git push origin "$tag"
    notes=(--generate-notes)
    [[ -n "${NOTES_FILE:-}" ]] && notes=(--notes-file "$NOTES_FILE")
    gh release create "$tag" "$dmg" "$dmg.sha256" --title "Waypoint $version" --verify-tag "${notes[@]}"
fi
