#!/bin/zsh
# Builds a signed, notarized and stapled Waypoint DMG plus the Sparkle appcast
# that installed copies update from, and publishes them like snippets does:
# the DMG and appcast go to S3 (Yandex Object Storage), which is the live
# update feed, and the DMG is mirrored as a GitHub release.
#
#   scripts/release.sh 0.2.0             # → dist/Waypoint-0.2.0.dmg (+ .sha256, appcast.xml)
#   scripts/release.sh 0.2.0 --publish   # …tag v0.2.0, upload to S3, create the GitHub release
#
# --publish needs S3 credentials in AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY,
# or in scripts/release.env (gitignored, same format as snippets' Distribution/.env).
#
#   SIGN_IDENTITY   Developer ID Application identity (default: first one in the keychain)
#   NOTARY_PROFILE  notarytool keychain profile (default: NotaryProfile). Create it once:
#                     xcrun notarytool store-credentials NotaryProfile --apple-id <apple id> --team-id <team id>
#   NOTARY_KEY, NOTARY_KEY_ID, NOTARY_ISSUER
#                   or notarize with an App Store Connect API key (.p8 path, key ID, issuer ID)
#   NOTES_FILE      release notes for --publish (default: generated by GitHub)
#   Sparkle signing key: the private EdDSA key in the keychain under account "waypoint"
#                   (generate_keys --account waypoint); its public half is in scripts/bundle.sh.
#   ALLOW_DIRTY=1   build from a working tree with uncommitted changes
set -euo pipefail
cd "${0:A:h}/.."

step() { print -P "%F{cyan}==>%f $*" }
fail() { print -P "%F{red}error:%f $*" >&2; exit 1 }

version="${1:-}"
publish=0
[[ "${2:-}" == "--publish" ]] && publish=1
[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "usage: scripts/release.sh <x.y.z> [--publish]"

tag="v$version"
repo_url="https://github.com/wowlocal/waypoint-launcher"
# Where updates are served from. Fixed on purpose, not configurable: installed
# copies have this feed baked in (scripts/bundle.sh), and the bucket is shared
# with other apps, so a stray S3_PREFIX must never redirect an upload.
s3_endpoint="https://storage.yandexcloud.net"
s3_region="ru-central1"
s3_bucket="macos-releases"
s3_prefix="waypoint"
public_base="$s3_endpoint/$s3_bucket/$s3_prefix"
feed_url="$public_base/appcast.xml"
s3() { aws s3 "$@" --endpoint-url "$s3_endpoint" --region "$s3_region" }

if [[ -f scripts/release.env ]]; then
    set -a
    source scripts/release.env
    set +a
fi
sparkle_bin=".build/artifacts/sparkle/Sparkle/bin"
profile="${NOTARY_PROFILE:-NotaryProfile}"
# Separate from build/Waypoint.app, which may be running.
app="build/release/Waypoint.app"
dist="dist"
dmg="$dist/Waypoint-$version.dmg"

# Preconditions first, so a missing credential doesn't cost a full build.
[[ -z "$(git status --porcelain)" || -n "${ALLOW_DIRTY:-}" ]] \
    || fail "working tree has uncommitted changes (ALLOW_DIRTY=1 to build anyway)"
identity="${SIGN_IDENTITY:-$(security find-identity -v -p codesigning | sed -n 's/.*"\(Developer ID Application:.*\)"/\1/p' | awk 'NR == 1')}"
[[ -n "$identity" ]] || fail "no Developer ID Application identity in the keychain"
if [[ -n "${NOTARY_KEY:-}" ]]; then
    [[ -n "${NOTARY_KEY_ID:-}" && -n "${NOTARY_ISSUER:-}" ]] || fail "NOTARY_KEY also needs NOTARY_KEY_ID and NOTARY_ISSUER"
    notary_auth=(--key "$NOTARY_KEY" --key-id "$NOTARY_KEY_ID" --issuer "$NOTARY_ISSUER")
    xcrun notarytool history "${notary_auth[@]}" >/dev/null 2>&1 || fail "Apple rejected the App Store Connect API key"
else
    notary_auth=(-p "$profile")
    xcrun notarytool history "${notary_auth[@]}" >/dev/null 2>&1 || fail "notarytool profile \"$profile\" is missing. Create it once with:
    xcrun notarytool store-credentials $profile --apple-id <apple id> --team-id <team id>
or set NOTARY_KEY, NOTARY_KEY_ID and NOTARY_ISSUER to use an App Store Connect API key"
fi
# Sparkle tools come with the package; resolve it if this is a fresh checkout.
[[ -x "$sparkle_bin/generate_appcast" ]] || xcrun swift package resolve
private_key_public_half="$("$sparkle_bin/generate_keys" --account waypoint -p 2>/dev/null || true)"
[[ -n "$private_key_public_half" ]] || fail "no Sparkle signing key in the keychain (account \"waypoint\")"
[[ "$(<scripts/bundle.sh)" == *"sparkle_public_key=\"$private_key_public_half\""* ]] \
    || fail "the keychain's Sparkle key doesn't match the public key in scripts/bundle.sh; updates would be rejected"
if (( publish )); then
    ! git rev-parse -q --verify "refs/tags/$tag" >/dev/null || fail "tag $tag already exists"
    git fetch -q origin
    git merge-base --is-ancestor HEAD origin/main || fail "HEAD is not on origin/main; push it first"
    gh auth status >/dev/null 2>&1 || fail "gh is not logged in"
    command -v aws >/dev/null || fail "aws CLI not found (brew install awscli)"
    # List the bucket, not the prefix: `aws s3 ls` exits 1 on an empty prefix (the first release).
    s3 ls "s3://$s3_bucket/" >/dev/null || fail "can't reach s3://$s3_bucket/; check the S3 credentials"
fi

step "Testing"
xcrun swift test

step "Building Waypoint $version"
APP_PATH="$app" VERSION="$version" SIGN_IDENTITY="$identity" scripts/bundle.sh
codesign --verify --deep --strict "$app"
[[ "$(/usr/libexec/PlistBuddy -c 'Print SUFeedURL' "$app/Contents/Info.plist")" == "$feed_url" ]] \
    || fail "the app's SUFeedURL doesn't match $feed_url"
# Capture first: `grep -q` exits early and pipefail would count codesign's SIGPIPE as failure.
signature="$(codesign -dvv "$app" 2>&1)"
[[ "$signature" == *"(runtime)"* ]] || fail "hardened runtime is not enabled"

# notarize <file>: submit, wait, and on rejection print Apple's log.
notarize() {
    local file="$1" result
    result="$(mktemp)"
    step "Notarizing ${file:t} (usually a few minutes)"
    xcrun notarytool submit "$file" "${notary_auth[@]}" --wait --timeout 1h --output-format json >"$result" || true
    local notary_status id
    notary_status="$(plutil -extract status raw -o - "$result" 2>/dev/null || echo unknown)"
    if [[ "$notary_status" != "Accepted" ]]; then
        cat "$result" >&2
        id="$(plutil -extract id raw -o - "$result" 2>/dev/null || true)"
        [[ -n "$id" ]] && xcrun notarytool log "$id" "${notary_auth[@]}" >&2
        fail "notarization of ${file:t}: $notary_status"
    fi
    rm -f "$result"
}

rm -rf "$dist"
mkdir -p "$dist"

# The app first, so it carries its own ticket even outside the DMG.
zip="$dist/Waypoint-$version-app.zip"
ditto -c -k --keepParent "$app" "$zip"
notarize "$zip"
rm -f "$zip"
xcrun stapler staple "$app"

step "Packaging $dmg"
staging="$(mktemp -d)"
mount="$(mktemp -d)"
trap 'rm -rf "$staging"; hdiutil detach -quiet "$mount" 2>/dev/null || true; rmdir "$mount" 2>/dev/null || true' EXIT
ditto "$app" "$staging/Waypoint.app"
ln -s /Applications "$staging/Applications"
hdiutil create -quiet -volname "Waypoint $version" -srcfolder "$staging" -fs HFS+ -format UDZO -ov "$dmg"
codesign --force --sign "$identity" --timestamp "$dmg"
notarize "$dmg"
xcrun stapler staple "$dmg"

step "Verifying"
xcrun stapler validate "$dmg"
spctl --assess --type open --context context:primary-signature --verbose "$dmg"
hdiutil attach -quiet -nobrowse -readonly -mountpoint "$mount" "$dmg"
spctl --assess --type execute --verbose "$mount/Waypoint.app"
xcrun stapler validate "$mount/Waypoint.app"
hdiutil detach -quiet "$mount"
(cd "$dist" && shasum -a 256 "${dmg:t}" >"${dmg:t}.sha256")

step "Generating appcast"
feed_dir="$(mktemp -d)"
cp "$dmg" "$feed_dir/"
# One item per release (the newest), and no deltas: the app is ~2 MB.
"$sparkle_bin/generate_appcast" --account waypoint --maximum-deltas 0 \
    --download-url-prefix "$public_base/" --link "$repo_url" \
    -o "$dist/appcast.xml" "$feed_dir"
rm -rf "$feed_dir"
signature="$(sed -n 's/.*sparkle:edSignature="\([^"]*\)".*/\1/p' "$dist/appcast.xml" | awk 'NR == 1')"
[[ -n "$signature" ]] || fail "appcast has no EdDSA signature"
"$sparkle_bin/sign_update" --verify "$dmg" "$signature" || fail "appcast signature doesn't match the DMG"
grep -q "url=\"$public_base/${dmg:t}\"" "$dist/appcast.xml" || fail "appcast points somewhere unexpected"
print -P "%F{green}Ready:%f $dmg"

if (( publish )); then
    step "Publishing $tag"
    git tag -a "$tag" -m "Waypoint $version"
    git push origin "$tag"

    # The DMG first and the appcast last, so the live feed never points at a
    # file that isn't there yet.
    step "Uploading to s3://$s3_bucket/$s3_prefix/"
    s3 cp "$dmg" "s3://$s3_bucket/$s3_prefix/${dmg:t}" --content-type application/x-apple-diskimage
    [[ "$(curl -fsI "$public_base/${dmg:t}" | awk 'tolower($1) == "content-length:" { print $2 + 0 }')" == "$(stat -f %z "$dmg")" ]] \
        || fail "$public_base/${dmg:t} isn't publicly served at the right size"
    s3 cp "$dist/appcast.xml" "s3://$s3_bucket/$s3_prefix/appcast.xml" --content-type application/xml --cache-control no-cache
    curl -fs "$feed_url" | cmp -s - "$dist/appcast.xml" || fail "the public feed at $feed_url doesn't match the new appcast"
    print -P "%F{green}Live:%f $feed_url"

    step "Mirroring to GitHub Releases"
    notes=(--generate-notes)
    [[ -n "${NOTES_FILE:-}" ]] && notes=(--notes-file "$NOTES_FILE")
    gh release create "$tag" "$dmg" "$dmg.sha256" --title "Waypoint $version" --verify-tag "${notes[@]}"
fi
